project_id = "mqtowxaxwanovvjdktpq"

[functions.discord-notify]
verify_jwt = false

[functions.paypal-purchase]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.nowpayments]
verify_jwt = false
