// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtdhvmhdszbzwiqvdhee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0ZGh2bWhkc3piendpcXZkaGVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMDc2OTgsImV4cCI6MjA4ODU4MzY5OH0.hFk1QJY3U6B4orXUrxp3VK-YEQjsWMKrW7ltCC5jf8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});