// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqtowxaxwanovvjdktpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xdG93eGF4d2Fub3Z2amRrdHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNDIzNjQsImV4cCI6MjA4ODYxODM2NH0.8FiWJi_5_Q8lYZ7u2fQPjxAlLX5BWm3ctj_IKCzRjUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});